/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChapterResponseDto { 
    id?: number;
    title?: string;
    content?: string;
    chapterOrder?: number;
    status?: ChapterResponseDto.StatusEnum;
    publishDate?: string;
    views?: number;
    votes?: number;
    commentsCount?: number;
    authorNotes?: string;
    readTimeMinutes?: number;
    wordCount?: number;
    createdAt?: string;
    updatedAt?: string;
    published?: boolean;
}
export namespace ChapterResponseDto {
    export const StatusEnum = {
        Draft: 'DRAFT',
        Published: 'PUBLISHED',
        Archived: 'ARCHIVED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


