/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConversationBoardPostResponseDto { 
    id?: number;
    content?: string;
    posterUsername?: string;
    ownerUsername?: string;
    postedAt?: string;
    parentId?: number;
    replies?: Array<ConversationBoardPostResponseDto>;
    reply?: boolean;
}

