/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FollowResponseDto } from './followResponseDto';


export interface FollowDto { 
    followers?: Array<FollowResponseDto>;
    following?: Array<FollowResponseDto>;
}

