/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReadingListItemResponseDto } from "./readingListItemResponseDto";


export interface ReadingListResponseDto {
    id?: number;
    name?: string;
    ownerId?: number;
    ownerUsername?: string;
    storyCount?: number;
    items?: Array<ReadingListItemResponseDto>;
    'private'?: boolean;
}

