/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReadingListItemResponseDto } from "./readingListItemResponseDto";


export interface ReadingListResponseDto {
    id?: number;
    name?: string;
    ownerId?: number;
    ownerUsername?: string;
    storyCount?: number;
    items?: Array<ReadingListItemResponseDto>;
    readingListType?: ReadingListResponseDto.ReadingListTypeEnum;
    'private'?: boolean;
}
export namespace ReadingListResponseDto {
    export const ReadingListTypeEnum = {
        Default: 'DEFAULT',
        Liked: 'LIKED',
        Custom: 'CUSTOM'
    } as const;
    export type ReadingListTypeEnum = typeof ReadingListTypeEnum[keyof typeof ReadingListTypeEnum];
}


