/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserStats } from './userStats';
import { UserProfile } from './userProfile';


export interface User { 
    id?: number;
    firstName?: string;
    lastName?: string;
    userName?: string;
    password?: string;
    profile?: UserProfile;
    stats?: UserStats;
}

