export enum CategoryEnum {
  ACTION = 'ACTION',
  ADVENTURE = 'ADVENTURE',
  CHICKLIT = 'CHICKLIT',
  FANFICTION = 'FANFICTION',
  FANTASY = 'FANTASY',
  GENERAL_FICTION = 'GENERAL_FICTION',
  HISTORICAL_FICTION = 'HISTORICAL_FICTION',
  HORROR = 'HORROR',
  HUMOR = 'HUMOR',
  MYSTERY_THRILLER = 'MYSTERY_THRILLER',
  NON_FICTION = 'NON_FICTION',
  PARANORMAL = 'PARANORMAL',
  POETRY = 'POETRY',
  RANDOM = 'RANDOM',
  ROMANCE = 'ROMANCE',
  SCIENCE_FICTION = 'SCIENCE_FICTION',
  SHORT_STORY = 'SHORT_STORY',
  SPIRITUAL = 'SPIRITUAL',
  TEEN_FICTION = 'TEEN_FICTION',
  VAMPIRE = 'VAMPIRE',
  WEREWOLF = 'WEREWOLF',
}

export const CategoryLabels: Record<CategoryEnum, string> = {
  [CategoryEnum.ACTION]: 'Action',
  [CategoryEnum.ADVENTURE]: 'Adventure',
  [CategoryEnum.CHICKLIT]: 'Chicklit',
  [CategoryEnum.FANFICTION]: 'Fanfiction',
  [CategoryEnum.FANTASY]: 'Fantasy',
  [CategoryEnum.GENERAL_FICTION]: 'General Fiction',
  [CategoryEnum.HISTORICAL_FICTION]: 'Historical Fiction',
  [CategoryEnum.HORROR]: 'Horror',
  [CategoryEnum.HUMOR]: 'Humor',
  [CategoryEnum.MYSTERY_THRILLER]: 'Mystery Thriller',
  [CategoryEnum.NON_FICTION]: 'Non Fiction',
  [CategoryEnum.PARANORMAL]: 'Paranormal',
  [CategoryEnum.POETRY]: 'Poetry',
  [CategoryEnum.RANDOM]: 'Random',
  [CategoryEnum.ROMANCE]: 'Romance',
  [CategoryEnum.SCIENCE_FICTION]: 'Science Fiction',
  [CategoryEnum.SHORT_STORY]: 'Short Story',
  [CategoryEnum.SPIRITUAL]: 'Spiritual',
  [CategoryEnum.TEEN_FICTION]: 'Teen Fiction',
  [CategoryEnum.VAMPIRE]: 'Vampire',
  [CategoryEnum.WEREWOLF]: 'Werewolf',
};
