import { StoryRequestDto } from "../../models/storyRequestDto";

export const CategoryLabels: Record<StoryRequestDto.CategoryEnum, string> = {
  ACTION: 'Action',
  ADVENTURE: 'Adventure',
  CHICKLIT: 'Chicklit',
  FANFICTION: 'Fanfiction',
  FANTASY: 'Fantasy',
  GENERAL_FICTION: 'General Fiction',
  HISTORICAL_FICTION: 'Historical Fiction',
  HORROR: 'Horror',
  HUMOR: 'Humor',
  MYSTERY_THRILLER: 'Mystery Thriller',
  NON_FICTION: 'Non Fiction',
  PARANORMAL: 'Paranormal',
  POETRY: 'Poetry',
  RANDOM: 'Random',
  ROMANCE: 'Romance',
  SCIENCE_FICTION: 'Science Fiction',
  SHORT_STORY: 'Short Story',
  SPIRITUAL: 'Spiritual',
  TEEN_FICTION: 'Teen Fiction',
  VAMPIRE: 'Vampire',
  WEREWOLF: 'Werewolf',
};
