import { StoryRequestDto } from '../../models/storyRequestDto';

export const LanguageLabels: Record<StoryRequestDto.LanguageEnum, string> = {
  POLSKI: 'Polski',
  ARABIC: 'Arabic',
  CZECH: 'Czech',
  DEUTSCH: 'Deutsch',
  GREEK: 'Greek',
  ENGLISH: 'English',
  SPANISH: 'Spanish',
  FARSI: 'Farsi',
  FILIPINO: 'Filipino',
  FRENCH: 'French',
  HINDI: 'Hindi',
  BAHASA_INDONESIA: 'Bahasa Indonesia',
  ITALIANO: 'Italiano',
  HEBREW: 'Hebrew',
  MAGYAR: 'Magyar',
  BAHASA_MELAYU: 'Bahasa Melayu',
  NEDERLANDS: 'Nederlands',
  PORTUGUESE: 'Portuguese',
  ROMANIAN: 'Romanian',
  RUSSIAN: 'Russian',
  SLOVAK: 'Slovak',
  SERBIAN: 'Serbian',
  TURKISH: 'Turkish',
  UKRAINIAN: 'Ukrainian',
  VIETNAMESE: 'Vietnamese',
  OTHER: 'Other',
};
