export enum LanguageEnum {
  POLSKI = 'pl',
  ARABIC = 'ar',
  CZECH = 'cs',
  DEUTSCH = 'de',
  GREEK = 'el',
  ENGLISH = 'en',
  SPANISH = 'es',
  FARSI = 'fa',
  FILIPINO = 'fil',
  FRENCH = 'fr',
  HINDI = 'hi',
  BAHASA_INDONESIA = 'id',
  ITALIANO = 'it',
  HEBREW = 'he',
  MAGYAR = 'hu',
  BAHASA_MELAYU = 'ms',
  NEDERLANDS = 'nl',
  PORTUGUESE = 'pt',
  ROMANIAN = 'ro',
  RUSSIAN = 'ru',
  SLOVAK = 'sk',
  SERBIAN = 'sr',
  TURKISH = 'tr',
  UKRAINIAN = 'uk',
  VIETNAMESE = 'vi',
  OTHER = 'other'
}

export const LanguageLabels: Record<LanguageEnum, string> = {
  [LanguageEnum.POLSKI]: 'Polski',
  [LanguageEnum.ARABIC]: 'Arabic',
  [LanguageEnum.CZECH]: 'Czech',
  [LanguageEnum.DEUTSCH]: 'Deutsch',
  [LanguageEnum.GREEK]: 'Greek',
  [LanguageEnum.ENGLISH]: 'English',
  [LanguageEnum.SPANISH]: 'Spanish',
  [LanguageEnum.FARSI]: 'Farsi',
  [LanguageEnum.FILIPINO]: 'Filipino',
  [LanguageEnum.FRENCH]: 'French',
  [LanguageEnum.HINDI]: 'Hindi',
  [LanguageEnum.BAHASA_INDONESIA]: 'Bahasa Indonesia',
  [LanguageEnum.ITALIANO]: 'Italiano',
  [LanguageEnum.HEBREW]: 'Hebrew',
  [LanguageEnum.MAGYAR]: 'Magyar',
  [LanguageEnum.BAHASA_MELAYU]: 'Bahasa Melayu',
  [LanguageEnum.NEDERLANDS]: 'Nederlands',
  [LanguageEnum.PORTUGUESE]: 'Portuguese',
  [LanguageEnum.ROMANIAN]: 'Romanian',
  [LanguageEnum.RUSSIAN]: 'Russian',
  [LanguageEnum.SLOVAK]: 'Slovak',
  [LanguageEnum.SERBIAN]: 'Serbian',
  [LanguageEnum.TURKISH]: 'Turkish',
  [LanguageEnum.UKRAINIAN]: 'Ukrainian',
  [LanguageEnum.VIETNAMESE]: 'Vietnamese',
  [LanguageEnum.OTHER]: 'Other'
};
